feat: currencies settings page
vultisig/vultisig-windows pull request #216
Opened 2024-09-17 17:47 UTC by antoni0dev

Currency Settings Page UI
Implement Global Currency around the application and adjust calculations based on it.

Acceptance criteria:

Open the settings;
Open the settings > Select the currency that comes from the Enum Fiat;
Open the settings > Click on the currency;
Open the settings > Click on the currency > Make the selected currency the chosen one on the list;
After changing the FIAT it should change all the currencies from the listing page.
After changing the FIAT it should change all the currencies from the listing page details.
After changing the FIAT it should change all the currencies on the sending page
After change the FIAT it should change all the currencies on the sending page verify

2024-09-17 20:35 UTC, enriquesouza requested changes
Please, lets remove any hardcode from the currency.

2024-09-17 20:35 UTC, enriquesouza commented on frontend/src/pages/vaultSettings/vaultCurrency/constants.ts
> +  {
Can we not hardcode it? Some formatters already give the currency symbols and punctuation.

2024-09-17 20:35 UTC, enriquesouza commented on frontend/src/i18n/locales/en/translation.json
> +  "vault_settings_currency_settings_title_usd": "USD",
Can we not hardcode it?

2024-09-17 20:38 UTC, enriquesouza commented on frontend/src/i18n/locales/en/translation.json
> +  "vault_settings_currency_settings_title_usd": "USD",
```function formatCurrency(
  amount: number,
  currency: string = 'USD',
  locale?: string // Optional locale
): string {
  return new Intl.NumberFormat(locale || undefined, {
    style: 'currency',
    currency: currency,
  }).format(amount);
}

// Example usage
const formattedAmount = formatCurrency(1234567.89, GLOBAL_SELECTED_FIAT);
console.log(formattedAmount); // Output depends on the user's environment locale

const formattedEuro = formatCurrency(1234567.89, 'EUR');
console.log(formattedEuro); // Output depends on the user's environment locale
```

2024-09-18 07:13 UTC, rcoderdev commented on frontend/src/lib/hooks/useGlobalCurrency/index.ts
> +  return {
`export const useGlobalCurrency = () => {
  return usePersistentState(
    PersistentStateKey.Currency,
    currencies[0]
  );
  }`
  
 No need to return an object here. If you want - you can have a separate hook for a symbol. 
 
 `changeGlobalCurrency: (newCurrency: Fiat) => setGlobalCurrency(newCurrency)`  - no need in this.

2024-09-18 07:15 UTC, rcoderdev commented on frontend/src/router.tsx
> +    path: '/vault/settings/currency-settings',
Let's add new paths to `navigation/index.ts`

2024-09-18 20:17 UTC, enriquesouza approved these changes
LGTM

2024-09-18 20:17 UTC, merged