Fix/generated memo for throchain function
vultisig/vultisig-windows pull request #677
Opened 2024-12-16 20:29 UTC by antoni0dev

fix memo generation for throchain function.
https://github.com/vultisig/vultisig-windows/issues/663

2024-12-16 20:49 UTC, enriquesouza approved these changes

2024-12-16 20:54 UTC, johnnyluo requested changes
see comments

2024-12-16 20:54 UTC, johnnyluo commented on frontend/src/vault/deposit/utils/memoGenerator/index.ts
> +        ? `BOND:${nodeAddress}:${amount}:${operatorFee}`
this one is wrong , `amount` is not part of the memo 

FYI: https://dev.thorchain.org/concepts/memos.html#bond-unbond-and-leave

2024-12-17 10:52 UTC, johnnyluo approved these changes
LGTM

2024-12-17 12:26 UTC, merged